version: "3.3"
services:
  database:
    build:
      context: ./database/image
      dockerfile: Dockerfile
    networks:
      rpki:
        aliases:
          - db
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASS=dev
    depends_on:
      - rpkival
    volumes:
      - "/var/lib/repos/rpki-dashboard/collector:/collector/scripts"
      - "/var/lib/repos/rib-data:/collector/rib-data"
      - "/Users/npn/rpki-db:/var/lib/postgresql/data"
      - "/var/lib/repos/mrt-exports:/collector/mrt-exports"
  rpkival:
    image: ripencc/rpki-validator-3-docker
    networks:
      rpki:
        aliases:
          - rpkival
    privileged: true
    volumes:
      - "/var/lib/repos/rpki-dashboard/rpki/tals:/var/lib/rpki-validator-3/preconfigured-tals"
    ports:
      - "8080:8080"
  app:
    build:
      context: ./app/image
      dockerfile: Dockerfile
    environment:
      - PGHOST=db
      - PGUSER=dev
      - PGDATABASE=rpkilg
    networks:
      rpki:
        aliases:
          - app
    volumes:
      - "/var/lib/repos/rpki-dashboard/app/src:/app"
    ports:
      - "4000:4000"
  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      rpki:
        aliases:
          - proxy
  quagga:
    build:
      context: ./quagga
      dockerfile: Dockerfile
    ports:
      - "179:179"
    volumes:
      - "/var/lib/repos/mrt-exports:/mrt-exports"
    cap_add:
      - NET_ADMIN
      - NET_BROADCAST
    networks:
      rpki:
        aliases:
          - quagga
  rpkirtr:
    build:
      context: ./rpkirtr
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    networks:
      rpki:
        aliases:
          - rpkirtr
networks:
  rpki:
    driver: bridge
