version: "3.3"
services:
  #  bgpsrc:
  #    #image: mikenowak/exabgp
  #    build:
  #      context: ./bgpsrc/image
  #      dockerfile: Dockerfile
  #    networks:
  #      bgp:
  #        ipv4_address: 172.16.238.100
  #        aliases:
  #          - bgpsrc
  #    volumes:
  #      - "/var/lib/repos/rpki-dashboard/bgpsrc/exabgp:/etc/exabgp"
  #    command: sleep 100000
  #  bgpinject:
  #    image: mikenowak/exabgp
  #    networks:
  #      bgp:
  #        ipv4_address: 172.16.238.200
  #        aliases:
  #          - bgpinject
  #    ports:
  #      - "5001:5001"
  #    volumes:
  #      - "/var/lib/repos/rpki-dashboard/bgpinject/exabgp:/usr/etc/exabgp"
  database:
    build:
      context: ./database/image
      dockerfile: Dockerfile
    networks:
      bgp:
        aliases:
          - db
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASS=dev
    depends_on:
      - rpkival
    volumes:
      - "/var/lib/repos/rpki-dashboard/collector:/collector/scripts"
  rpkival:
    image: ripencc/rpki-validator-3-docker
    networks:
      bgp:
        aliases:
          - rpkival
    volumes:
      - "/var/lib/repos/rpki-dashboard/rpki/tals:/var/lib/rpki-validator-3/preconfigured-tals"
    ports:
      - "8080:8080"
networks:
  bgp:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
